# Produce MS Word Docx file from all the individual Markdown files in folder
# David's **simple as can be**  Makefile...

deck	: deck.md
	pandoc --reference-doc reference.docx -o Deck.docx deck.md


deck.md : HC-Card*.md 
	cp title.md deck.md # Meta data in Markdown for title
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-going-to-plan.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	# 24 cards
	cat deck.md HC-Card-build-broken.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-build-broken.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-build-broken.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-build-broken.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-build-broken.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	#
	cat deck.md HC-Card-wind-at-back.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-wind-at-back.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-wind-at-back.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-wind-at-back.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-wind-at-back.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	#
	cat deck.md HC-Card-got-bugs.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-got-bugs.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-got-bugs.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-got-bugs.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-got-bugs.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	#
	cat deck.md HC-Card-got-tech-debt.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-got-tech-debt.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-got-tech-debt.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-got-tech-debt.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-got-tech-debt.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	#
	cat deck.md HC-Card-fried-disk.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-fried-disk.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-fried-disk.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-fried-disk.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-fried-disk.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	#
	cat deck.md HC-Card-found-defect.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-found-defect.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-found-defect.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	#
	cat deck.md HC-Card-refactor-debt.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-refactor-debt.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	cat deck.md HC-Card-refactor-debt.md pagebreak.md >> deck-accumlator.md; rm deck.md; mv deck-accumlator.md deck.md
	#


# The all rule makes all the PDF files listed
all :  deck 
                        

# Remove all DOCS outputs
clean :
	rm -f Deck.docx 
	rm -f deck.md

# Remove all PDF outputs then build them again
rebuild : clean all
